"""empty message

Revision ID: 700cd655e7fb
Revises: dd69b3485df6
Create Date: 2022-11-12 15:11:26.277203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '700cd655e7fb'
down_revision = 'dd69b3485df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rating_vendor_id_key', 'rating', type_='unique')
    op.drop_constraint('rating_vendor_id_fkey', 'rating', type_='foreignkey')
    op.drop_column('rating', 'vendor_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('vendor_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('rating_vendor_id_fkey', 'rating', 'user', ['vendor_id'], ['user_id'])
    op.create_unique_constraint('rating_vendor_id_key', 'rating', ['vendor_id'])
    # ### end Alembic commands ###
