"""added bank table

Revision ID: a10660a57abb
Revises: ee026d0365db
Create Date: 2022-11-17 00:45:53.334754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a10660a57abb'
down_revision = 'ee026d0365db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'store', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'store', type_='unique')
    # ### end Alembic commands ###
