"""empty message

Revision ID: dd69b3485df6
Revises: 
Create Date: 2022-11-12 14:54:35.623755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd69b3485df6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('rater_name', sa.String(), nullable=False))
    op.add_column('rating', sa.Column('rater_image', sa.String(), nullable=False))
    op.drop_constraint('rating_user_id_key', 'rating', type_='unique')
    op.drop_constraint('rating_user_id_fkey', 'rating', type_='foreignkey')
    op.drop_column('rating', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('rating_user_id_fkey', 'rating', 'user', ['user_id'], ['user_id'])
    op.create_unique_constraint('rating_user_id_key', 'rating', ['user_id'])
    op.drop_column('rating', 'rater_image')
    op.drop_column('rating', 'rater_name')
    # ### end Alembic commands ###
