"""empty message

Revision ID: ee026d0365db
Revises: 700cd655e7fb
Create Date: 2022-11-12 15:11:41.818923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee026d0365db'
down_revision = '700cd655e7fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('vendor_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'rating', 'user', ['vendor_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rating', type_='foreignkey')
    op.drop_column('rating', 'vendor_id')
    # ### end Alembic commands ###
